BACK/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #joinFormapp의 urls를 추가했다
    path('joinFormapp/', include('joinFormapp.urls')),
    #pageapp 의 urls 추가
    path('', include('pageapp.urls')),
    #peopleApp urls 추가
    path('peopleApp/', include('peopleApp.urls')),
    #account 의 urls 추가 
    path('accounts/', include('accounts.urls')),
    #mypage의 urls 추가
    path('mypage/', include('mypage.urls')),
    path('activity/', include('activity.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

activity/urls.py
from django.urls import path
from .views import show_activity, upload
from django.conf.urls.static import static
from django.conf import settings

app_name = 'activity'


urlpatterns = [
    path('project/', show_activity, name='show_activity'),
    path('upload/', upload, name='upload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pageapp/urls.py
from django.urls import  path
from .views import *
from . import views

app_name = 'pageapp'

urlpatterns = [
 path('', views.index, name='index'),
 path('index/', views.index, name='index'),
 path('login/', views.login, name='login'),
 path('intro/', views.intro, name='intro'),
 path('act/', views.act, name='act'),

]

activity/models.py
from django.db import models



#사용자(로그인 파트에서_모델 끌어오기)

# Create your models here.

class Activity(models.Model):
    title = models.CharField(max_length=150, null=False, blank=False)
    description=models.TextField(null=False, blank=False)
    writeTime=models.DateTimeField(auto_now_add=True)

class ActivityImage(models.Model):
    activity=models.ForeignKey(Activity, on_delete=models.CASCADE)
    activityImage=models.ImageField(upload_to='image/',blank=True, null=True)


class ActivityUser(models.Model):
    activity=models.ForeignKey(Activity, on_delete=models.CASCADE)
    user_id=models.CharField(max_length=30, null=False)
    
class ActivityUserSay(models.Model):
    activity=models.ForeignKey(Activity, on_delete=models.CASCADE)
    user_id=models.ForeignKey(ActivityUser, on_delete=models.CASCADE)
    user_say=models.CharField(max_length=200, null=True, blank=False)

activity/views.py
from django.shortcuts import render, redirect,get_object_or_404
from .models import Activity, ActivityImage, ActivityUser, ActivityUserSay
from mypage.models import Profile

# Create your views here.

from django.shortcuts import render
from .models import Activity, ActivityImage, ActivityUser, ActivityUserSay

def show_activity(request):
    # Activity 모델에 있는 모든 활동 글들을 가져옴
    activities = Activity.objects.all()

    # 함께 작성된 것들끼리 묶어서 세트로 표현
    activity_sets = []
    for activity in activities:
        activity_set = {
            'activity': activity,
            'images': ActivityImage.objects.filter(activity=activity),
            'users': ActivityUser.objects.filter(activity=activity),
            'user_says': ActivityUserSay.objects.filter(activity=activity)
        }
        activity_sets.append(activity_set)

    return render(request, 'activity/activity.html', {'activity_sets': activity_sets})


def upload(request):
    profiles = Profile.objects.all()

    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')

        # Activity 모델 객체 생성
        activity_instance = Activity.objects.create(
            title=title,
            description=description
        )

        # 이미지 업로드 처리
        images = request.FILES.getlist('activityImage')
        for img in images:
            ActivityImage.objects.create(activity=activity_instance, activityImage=img)

        # 사용자 및 사용자의 말 업로드 처리
        users = request.POST.getlist('user_id')

        for user in users:
            user_instance=ActivityUser.objects.create(activity=activity_instance, user_id=user)

        says = request.POST.getlist('user_say')
        for say in says:
            ActivityUserSay.objects.create(activity=activity_instance, user_id=user_instance, user_say=say)

        return redirect('activity:show_activity')  # 업로드 성공 시 리다이렉트

    else:
        return render(request, 'activity/upload.html', {'profiles': profiles})

activity/templates/activity/activity.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/activity.css' %}">
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>

<div class="container">
    <div id="tops">
        <a href="{% url 'pageapp:index'%}" class="back_bt">
            <img src="{% static 'img/back_bt.png' %}" alt="Your Image" id="plus">
        </a>
        <p class="top">activity</p>
        <a href="{% url 'activity:upload' %}" class="plus_cont">
            <img src="{% static 'img/plus.png' %}" alt="Your Image" id="plus">
        </a>
    </div>
    
    {% for activity_set in activity_sets %}
        <div class="activity-set">

            <div class="activity-images">
                <h2 class="title">{{ activity_set.activity.title }}</h2>
                <div class="gallery">
                {% for image in activity_set.images %}
                    <img src="{{ image.activityImage.url }}" alt="Activity Image" class="inImage">
                {% endfor %}
                </div>
            </div>
            <div class="right">
                <h3>{{ activity_set.activity.description }}</h3>
                <div class="activity-users">
                    
                    {% for user in activity_set.users %}
                        <p>{{ user.user_id }}</p>
                    {% endfor %}
                </div>

                <div class="activity-user-says">
                    
                    {% for say in activity_set.user_says %}
                        <p>{{ say.user_say }}</p>
                    {% endfor %}
            </div>
            </div>
            
        </div>
        
    {% endfor %}
</div>

{% endblock %}

activity/templates/activity/upload.html
{% extends 'base.html' %}

{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/activity_upload.css' %}">


<div id="myModal" class="modal" style="display: none;">
    <p class="choose">사람을 선택해주세요</p>
    <span class="close" id="closeModal">완료</span>
    <div class="modal-content">
        
      <ul>
        {% for profile in profiles %}
          <li class="profile-item" data-profile-id="{{ profile.id }}" data-profile-photo-url="{{ profile.profile_photo.url }}">
            {{ profile.user.username }}
            <!-- 다른 프로필 정보 표시 -->
          </li>
        {% endfor %}
      </ul>
    </div>
</div>
<div id="Container">
    <form id="activityForm" action="{% url 'activity:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>activity</h1>
        <input type="text" id="title" class="input" name="title">
        <input type="text" id="description" class="input" name="description">
        <div id="addZone" class="input">
            <label id="addPhoto" for="activityImage" style="cursor: pointer;">사진 추가</label>
            <div id="selectedPhotoName"></div>
            <input type="file" name="activityImage" id="activityImage" multiple required style="display: none;">
            <label id="choicePeople" style="cursor: pointer;">사람 추가</label>
            <div id="selectedUsers"></div>
            <input type="hidden" name="selected_users" id="selectedUsersInput">
            <input type="hidden" name="selected_users_say" id="selectedUserSayInput">
        </div>
        
        <input type="submit" value="제출" id="submit">
    </form>
</div>
<script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
<script src="{% static 'js/activity_upload.js' %}"></script>

{% endblock %}