BACK/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #joinFormapp의 urls를 추가했다
    path('joinFormapp/', include('joinFormapp.urls')),
    #pageapp 의 urls 추가
    path('', include('pageapp.urls')),
    #peopleApp urls 추가
    path('peopleApp/', include('peopleApp.urls')),
    #account 의 urls 추가 
    path('accounts/', include('accounts.urls')),
    #mypage의 urls 추가
    path('mypage/', include('mypage.urls')),
    path('activity/', include('activity.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django import views
from django.urls import  path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
path('logout/', views.logout_view, name='logout'), 
]

mypage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='mypage'

urlpatterns = [
    path('<str:username>/',views.mypage, name='mypage'),
    path('<str:username>/mypage_edit/',views.mypage_edit, name='mypage_edit'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mypage/models.py
from django.db import models
from django.contrib.auth.models import User
from  django.db.models.signals import post_save
from django.dispatch import receiver
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)#현 계정의 사용자를 가져옴
    profile_photo = models.ImageField(blank=True, upload_to="profilePhoto/")#프로필 사진
    major = models.CharField(max_length=100, null=True, blank=True)#전공
    github = models.URLField(null=True, blank=True)#깃허브 링크
    tistory = models.URLField(null=True, blank=True)#티스토리 링크
    
    def __str__(self): #def __str__ 함수 없으면 객체 번호로 출력됨 ex) UserInfo(1)
        return self.user.username

    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

mypage/forms.py
from django import forms
from .models import Profile

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields=('profile_photo','major','github','tistory')

mypage/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required #로그인한 사용자만 사용 가능
from .models import Profile
# from . import ProfileForm

# mypage 화면
@login_required(login_url='accounts:login')
def mypage(request,username):
    username = request.user.username
    profile = get_object_or_404(Profile, user__username=username)
    return render(request, 'mypage.html', {'profile':profile})

# 개인 정보 수정하기
def mypage_edit(request, username):
    username = request.user.username
    profile = get_object_or_404(Profile, user__username=username)
    if request.method == 'POST':
        if request.POST.get('profile_photo', True):
            profile.profile_photo = request.FILES.get('profile_photo')
        profile.major = request.POST.get('major')
        profile.github = request.POST.get('github')
        profile.tistory = request.POST.get('tistory')
        profile.save()
        return redirect('mypage:mypage', username=username)
    else:
        return render(request, 'mypage_edit.html', {'profile':profile})
            

mypage/templates/mypage.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!--css-->
    <link rel="stylesheet" href="{% static 'css/mypage.css'%}">
    <!--js-->
    
    <!-- 마이 페이지 메인 -->
    <div id="page-name"><h1>my page</h1></div>
    <div class="container-info">
      <div class="info">
      <!-- 프로필 사진 -->
      <div id="photo">
        <div><img src={% if profile.profile_photo %}"{{ profile.profile_photo.url }}"{% else %}"https://i.stack.imgur.com/34AD2.jpg"{% endif %} class="no-edit" id="profile-photo" alt=""></div>
        <div></div>
      </div>
      <!-- 유저 정보 -->
      <div id="info">
        <h2>
        {% if request.user.is_authenticated %}
          <div>{{ request.user.first_name }}{{ request.user.last_name }}</div>
        {% endif %}
        <div>전공: {{ profile.major }}</div>
        <div>깃허브: <a href="{{ profile.github }}">{{ profile.github }}</a></div>
        <div>티스토리: <a href="{{ profile.tistory }}">{{ profile.tistory }}</a></div>
        
        </h2>
        <!-- 수정하기 버튼 -->
        <div id="edit"><button class="btn-edit" onclick="location.href='{% url 'mypage:mypage_edit' username=request.user.username %}'">Edit</button></div>
      </div>
      </div>
      

      <!-- 로그아웃 버튼 버튼 -->
      {%if user.is_authenticated%}
      <div id="logout"><button class="btn-logout" onclick="location.href='{% url 'accounts:logout' %}'" type="submit">Logout</button></div>
      {%endif%}
{% endblock %}

mypage/templates/mypage_edit.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <!--css-->    
    <link rel="stylesheet" href="{% static 'css/mypage.css'%}">
    <!--js-->
    <!-- 마이 페이지 수정 -->
    <div id="page-name"><h1>my page</h1></div>
    <div class="container-info">
        <form action="{% url 'mypage:mypage_edit' username=request.user.username %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="info">
                <!-- 프로필 사진 -->
                <div id="photo">
                    <div><img src={% if profile.profile_photo %}"{{ profile.profile_photo.url }}"{% else %}"https://i.stack.imgur.com/34AD2.jpg"{% endif %} id="profile-photo" alt=""></div>
                    <div><input type="file" name="profile_photo" value="{{ profile.profile_photo }}" id="select-photo"></div>
                </div>
                <!-- 유저 정보 -->
                <div id="userInfo">
                    <h2> 
                        {% if request.user.is_authenticated %}
                        <div>{{ request.user.first_name }}{{ request.user.last_name }}</div>
                        {% endif %}
                        <div>전공: <input type="text" name="major" value="{{profile.major}}"></div>
                        <div>깃허브: <input type="url" name="github" value="{{profile.github}}"></div>
                        <div>티스토리: <input type="url" name="tistory" value="{{profile.tistory}}"></div>
                    </h2>
                    <!-- 저장 버튼 -->
                    <div><input type="submit" value="save" class="btn-edit"></div>
                </div>
            </div>
        </form>
    </div>
{% endblock %}