BACK/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    #joinFormapp의 urls를 추가했다
    path('joinFormapp/', include('joinFormapp.urls')),
    #pageapp 의 urls 추가
    path('', include('pageapp.urls')),
    #peopleApp urls 추가
    path('peopleApp/', include('peopleApp.urls')),
    #account 의 urls 추가 
    path('accounts/', include('accounts.urls')),
    #mypage의 urls 추가
    path('mypage/', include('mypage.urls')),
    path('activity/', include('activity.urls')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django import views
from django.urls import  path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
path('login/', auth_views.LoginView.as_view(template_name="accounts/login.html"),name='login'),
path('logout/', views.logout_view, name='logout'), 
]

activity/urls.py
from django.urls import path
from .views import show_activity, upload
from django.conf.urls.static import static
from django.conf import settings

app_name = 'activity'


urlpatterns = [
    path('project/', show_activity, name='show_activity'),
    path('upload/', upload, name='upload'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mypage/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name='mypage'

urlpatterns = [
    path('<str:username>/',views.mypage, name='mypage'),
    path('<str:username>/mypage_edit/',views.mypage_edit, name='mypage_edit'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pageapp/urls.py
from django.urls import  path
from .views import *
from . import views

app_name = 'pageapp'

urlpatterns = [
 path('', views.index, name='index'),
 path('index/', views.index, name='index'),
 path('login/', views.login, name='login'),
 path('intro/', views.intro, name='intro'),
 path('act/', views.act, name='act'),

]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BEMORE+</title>
    <!--css-->
    <link rel="stylesheet" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    <!--js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script defer src="{% static 'js/mNav.js' %}"></script>
    <script src="https://kit.fontawesome.com/9dd3bbb56c.js" crossorigin="anonymous"></script><!--모바일 네비바 아이콘-->
    {% if not_date %}
        <script src="{% static 'js/already.js' %}" data-not-date="{{ not_date|yesno:"true,false" }}"></script>
    {% endif %}
</head>
<body>
    <div id='wrapper'>
    <header class="header">
        <nav class="navbar">
            <!-- 네비바 로고 -->
            <div class="nav_logo"><a href="{% url 'pageapp:index'%}"><h5>BEMORE+</h5></a></div>
           <!-- 네비바 메뉴 -->
            <ul class="nav_menu">
                <li id="etc"><a href="{% url 'activity:show_activity'%}">activity</a></li><!--활동 게시판-->
                <li id="etc"><a href="{% url 'peopleApp:people' %}">people</a></li><!--동아리원 소개 페이지--> 
                <li id="etc" class="menu1">
                    {%if user.is_authenticated %}
                         <a class="login-btn">login</a>
                         <ul id="submenu" class="sub1">
                            <li><a href="{% url 'mypage:mypage' username=request.user.username %}">mypage</a></li>
                        </ul>
                    {% else %}
                        <a href="{% url 'accounts:login' %}" class="login-btn">login</a>
                    {% endif %}
                </li>
                <li class="menu2">
                    <div class="join-btn">join</div>
                    <ul id="submenu" class="sub2">
                        <li><a href="{% url 'pageapp:login' %}">합격자 조회</a></li>
                        <li><a href="{% url 'joinFormapp:show_joinForm' %}">지원서 제출</a></li>
                    </ul>
                </li>
            </ul>
            <!-- 햄버거 메뉴 -->
            <div class="toggle-btn">
                <i class="fa-regular fa-plus"></i>
            </div>
        </nav>
    </header>
    {% block content %}

    {% endblock%}
</div>
    <footer id="copyright">
        <p>© 2024. BEMORE all rights reserved</p>
    </footer>
</body>

    
</html>